name: Unused Code Check

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unusedcodecheck:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Pick Xcode 16.4
      run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'
    - name: Install Dependencies
      run: swift package resolve
    - name: Run Periphery on MacOS
      run: |
        brew install periphery
        periphery scan
